// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe_401j6HH5pIvTXmtIDsGY_7Ax2lVTGI',
    appId: '1:1016721545751:web:3cf755c7b74484743d9a52',
    messagingSenderId: '1016721545751',
    projectId: 'jf-innova-app',
    authDomain: 'jf-innova-app.firebaseapp.com',
    storageBucket: 'jf-innova-app.firebasestorage.app',
    measurementId: 'G-SCNG40DXRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcWmB6Ltx9XkZaMuGwsKyiTWEyg0VdsTQ',
    appId: '1:1016721545751:android:81bff948439c46163d9a52',
    messagingSenderId: '1016721545751',
    projectId: 'jf-innova-app',
    storageBucket: 'jf-innova-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwK9rXb7_WHpU9_up3cMbXFro93CtVdIU',
    appId: '1:1016721545751:ios:f16314511b9cf0433d9a52',
    messagingSenderId: '1016721545751',
    projectId: 'jf-innova-app',
    storageBucket: 'jf-innova-app.firebasestorage.app',
    iosBundleId: 'com.example.jfInnovaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwK9rXb7_WHpU9_up3cMbXFro93CtVdIU',
    appId: '1:1016721545751:ios:f16314511b9cf0433d9a52',
    messagingSenderId: '1016721545751',
    projectId: 'jf-innova-app',
    storageBucket: 'jf-innova-app.firebasestorage.app',
    iosBundleId: 'com.example.jfInnovaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe_401j6HH5pIvTXmtIDsGY_7Ax2lVTGI',
    appId: '1:1016721545751:web:ba15ec82e172daa13d9a52',
    messagingSenderId: '1016721545751',
    projectId: 'jf-innova-app',
    authDomain: 'jf-innova-app.firebaseapp.com',
    storageBucket: 'jf-innova-app.firebasestorage.app',
    measurementId: 'G-8BG3FXWJW5',
  );
}
